### ISSUE TITLE
Add space between rows on team.html

### ISSUE THREAD

**Issue by claire-peters** [PursuanceProject/website#30]

**Comment by elimisteve** [comment]
@geistling Want to see a neat trick?

Instead of closing GitHub issues manually, you can do [what I did here](https://github.com/PursuanceProject/website/commit/7ff2882f0cf269fcd030cbfe5a8cb17cd33f3003) and create a multi-line commit message like:

```
Added the thing

Fixed #30
```

and when you push that commit to the default branch of the GitHub repo that has issue #30 , it'll close automatically! :tada:
